dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=appier_export setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: FSFYnNViErP7vX2ZXd2FOgN6cU6QKjIu0QElw/x1O0A2USanhoeucsRMbbvxQTMLG30vRKqhFvdW+gtICKr/ry3Ycxp7WDQFB3GqshoTCbNx6jF/2jW7I1RO8fV+g2QEEMYmIXVUdQdhzmtXWuTF/4jBxASwrvRGHvKGAJqjrUXwZjqhwhebp1J/1UclxHntxQ2O8U+htQjuebzXZq3c8nUdJlDKFaLWLOhDRE9hYYXHOCsNXY5X5Eh2faYVzbQDRIf/nHSb2UbM2eYxxNQiIb1gwOB+6dztxl9d9NM9BiKY5vN/N8V84sYKudlY95vCaeEGiS8GSPwPvPsirlNnetQwo70RF8DU0peYnjrRA7C3+SEHBHhkZJwCYpaGGISbaflqZCgXpk3flenIDTJrCYeOwZN7N8G97ySBUuqXHmKAYPgM1bZbKG8oBBAUzl8WModVlf6OhVFl6oXz8ETOTMeRFYRYVajspFhcUnBes6M88wnMHala7ozbRerS7UthGIJuG35CY1mE5QII2VRhHxzoNK2XUm4sUZciKZB2yTAb9uKEydGpHdy+hyJqNbP8Fr/I9zwEO9WyTl9dgcYWi3tsBVPpaBHr3XqFFiSgBSl4K+uvB/6Aa/Z0pmg6IOEwTJ6aMEA4i4chMsYyvgxv9wLLenamLdui+ysQrqYJgMY=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
